# On your fork, you can configure build logs to be written to an
# AWS S3 bucket by making sure the following variables have been
# set in your Travis CI repository settings page:
#
# - AWS_ACCESS_KEY_ID (display value in build log: No)
# - AWS_SECRET_ACCESS_KEY (display value in build log: No)
# - AWS_DEFAULT_REGION (display value in build log: Yes)
# - LSMB_AWS_UPLOAD_BUCKET (display value in build log: Yes)
#
# AWS_DEFAULT_REGION should be the region hosting your S3 bucket
# LSMB_AWS_UPLOAD_BUCKET should contain the name of the bucket to upload into


# run on GCE build as per suggested:
# https://github.com/travis-ci/travis-ci/issues/3251#issuecomment-219675294
sudo: false
dist: xenial
language: perl

notifications:
  webhooks: https://ledgersmb.org/webhook/travis_ci_notifications

env:
  global:
    - RELEASE_TESTING=1
    - PGUSER=postgres
    - PGPASSWORD=test
    - LSMB_TEST_DB=1
    - LSMB_NEW_DB=lsmbinstalltest
    - LSMB_BASE_URL="http://127.0.0.1:5000"
    - PSGI_BASE_URL="http://127.0.0.1:5001"
    - HARNESS_RULESFILE="t/testrules.yml"
    - PATH="$HOME/locallib/bin:$PATH"
    - PERL_LOCAL_LIB_ROOT="$HOME/locallib${PERL_LOCAL_LIB_ROOT+:}$PERL_LOCAL_LIB_ROOT"
    - PERL5LIB="$HOME/locallib/lib/perl5${PERL5LIB+:}$PERL5LIB"
    - PERL_MM_OPT="INSTALL_BASE=$HOME/locallib"
    - PERL_MB_OPT="--install_base=$HOME/locallib"
    - DEVEL_COVER_OPTIONS="+ignore,\"\.lttc\$\""

addons:
  apt:
    packages: &default_packages
      - python-pip
      - nginx
      - texlive-latex-recommended
      - texlive-xetex

matrix:
  include:
    - perl: '5.28'
      addons:
        postgresql: '9.6'
        apt:
          packages:
            - *default_packages
            - postgresql-9.6-pgtap
      env:
        - BROWSER=chrome
        - CHROMEDRIVER=2.42
    - perl: '5.26'
      addons:
        postgresql: '9.6'
        apt:
          packages:
            - *default_packages
            - postgresql-9.6-pgtap
      env:
        - BROWSER=chrome
        - CHROMEDRIVER=2.42
    - perl: '5.24'
      addons:
        firefox: '57.0'
        postgresql: '9.6'
        apt:
          packages:
            - *default_packages
            - postgresql-9.6-pgtap
      env:
        - DOJO_BUILT=0
        - BROWSER=firefox
        - GECKODRIVER=0.21.0
    - perl: '5.22'
      addons:
        postgresql: "9.6"
        apt:
          packages:
            - *default_packages
            - postgresql-9.6-pgtap
            - phantomjs
      env:
        - COVERAGE=1
        - BROWSER=phantomjs
    - perl: '5.20'
      addons:
        firefox: '57.0'
        postgresql: "9.6"
        apt:
          packages:
            - *default_packages
            - postgresql-9.6-pgtap
      env:
        - COA_TESTING=1
        - BROWSER=firefox
        - GECKODRIVER=0.21.0
        #- MOZ_HEADLESS=1
    - perl: '5.18'
      addons:
        postgresql: "9.6"
        apt:
          packages:
            - *default_packages
            - postgresql-9.6-pgtap
      env:
        - DB_TESTING=1
        - BROWSER=chrome

before_cache:
  - mkdir -p $HOME/dojo_archive

cache:
  directories:
    - $HOME/locallib
    - $HOME/dojo_archive
    - $HOME/perl5

before_install:
  # list all the running services before we start. Perhaps we can stop some of them to save resources.
  - service --status-all
  # display the available resources
  - utils/diagnostics/t/01-system-resources.t
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl 2>/dev/null
  - perl -V
  - npm install uglify-js@">=2.0 <3.0"
  - pip install awscli --upgrade --user

install:
  # Suppress warnings in Perl 5.28 about Locale::* being moved out of 'core'
  # Further more is there a warning regarding redifinition of JSON::PP::Boolean
  # which is fixed in 4.03 (so, reinstall, in order to get to newest)
  - cpanm --reinstall --notest Locale::Country Locale::Codes Locale::Language JSON::PP
  - cpanm Cpanel::JSON::XS~3.0206
  - cpanm --quiet --notest --installdeps --with-develop --with-feature=edi --with-feature=latex-pdf-ps --with-feature=openoffice  --with-feature=starman --with-feature=xls .
  # Patch Weasel for headless tests on S::R::D
  - sudo ls -l `sudo find / -name Selenium2.pm`
  - chmod -R +w /home/travis/locallib/lib/perl5/Weasel /home/travis/locallib/lib/perl5/Selenium
  - cp -Rv utils/test/Weasel utils/test/Selenium /home/travis/locallib/lib/perl5
  # Patch--
  - if [ "$COVERAGE" == "1" ] ; then cpan-install --coverage ; fi
  - |
    case "${BROWSER}" in
      "chrome")
        wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        #Trusty packages are lagging too much. With 2.41 driver, we need Chrome 67-69
        sudo apt-get install -y libappindicator1 libappindicator3-1 libindicator3-7 libdbusmenu-gtk3-4 fonts-liberation
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome*.deb
        chromedriver --version
        google-chrome --version
        ;;
      "firefox")
        # Firefox has no deb package for geckodriver
        wget -q https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER}/geckodriver-v${GECKODRIVER}-linux64.tar.gz
        tar -xzf geckodriver-v${GECKODRIVER}-linux64.tar.gz -C ~/
        chmod +x ~/geckodriver
        rm geckodriver-v${GECKODRIVER}-linux64.tar.gz
        firefox --version
        ~/geckodriver --version
        ;;
      "phantomjs")
        phantomjs --version
        ;;
    esac

before_script:
  - make dist DIST_VER=travis DIST_DIR=${HOME}/built-dist/tar-output
  - cd ${HOME}/built-dist
  - tar xzf tar-output/ledgersmb-travis.tar.gz
  - cd ledgersmb
  - cp doc/conf/ledgersmb.conf.default ledgersmb.conf
  - cp t/.proverc ./
  - if [ "$COVERAGE" == "1" ] ; then coverage-setup 2>/dev/null ; fi
  - export DEVEL_COVER_OPTIONS=+ignore,"\.lttc\$"
  - sed -e "s#{ROOT}#$PWD#" doc/conf/nginx-travis.conf >/tmp/nginx.conf
  # Browser specifics
  - unset DISPLAY
  - |
    case "${BROWSER}" in
      "chrome")
        ((chromedriver --port=4422 --log-level=WARNING --url-base=wd/hub > /tmp/chrome.log 2>&1 &) && echo "Chrome started succesfully") || (echo "Failed to start Chrome!" ; cat /tmp/chrome.log ; exit 1)
        ;;
      "firefox")
        ((~/geckodriver --port 4422 --marionette-port 2828 --log warn > /tmp/firefox.log 2>&1 &) && echo "Firefox started succesfully") || (echo "Failed to start Firefox!" ; cat /tmp/firefox.log ; exit 1)
        ;;
      "phantomjs")
        ((phantomjs --webdriver=4422 --webdriver-loglevel=WARN > /tmp/phantomjs.log 2>&1 &) && echo "PhantomJS started succesfully") || (echo "Failed to start PhantomJS!" ; cat /tmp/phantomjs.log ; exit 1)
        ;;
    esac
  # Make sure the Browser server works
  - perl ./utils/test/check_headless_browser.pl ${BROWSER}
  # Start the PSGI
  - PERL5OPT="$PERL5OPT $HARNESS_PERL_SWITCHES" plackup -Ilib --port 5001 --server HTTP::Server::PSGI bin/ledgersmb-server.psgi --access_log /tmp/plackup-access.log 2> /tmp/plackup-error.log &
  - utils/test/Is_LSMB_running.sh --early # fail early if starman is not running (can be skipped based on reponame or owner by setting an array in the script)
  - nginx -c /tmp/nginx.conf
  - if [ "${DOJO_BUILT}" != "" ]; then sed -i -e "s#dojo_built *= *(\d)+#dojo_built={dojo_built}#" ledgersmb.conf ; fi
  # display the available resources
  - utils/diagnostics/t/01-system-resources.t
  - |
    mkdir screens
    sed -i -e 's/post-step: 0/post-step: 1/' t/.pherkin.yaml
    sed -i -e 's/# logging_dir:/logging_dir:/' t/.pherkin.yaml

script:
  - sudo ls -l `sudo find / -name Selenium2.pm`
  - BROWSER=${BROWSER}
      prove --jobs $(test-jobs) --recurse
            --pgtap-option dbname=lsmbinstalltest
            --pgtap-option username=postgres
            --feature-option tags=~@wip
          t/ xt/

after_script:
  # display the available resources
  - utils/diagnostics/t/01-system-resources.t
  - |
    if [ -n "$AWS_ACCESS_KEY_ID" ];
    then
       (cd "$HOME/built-dist/ledgersmb/screens"
        aws_url="s3://$LSMB_AWS_UPLOAD_BUCKET/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER"
        aws s3 cp --recursive --acl public-read ./ "$aws_url/screens"
        aws s3 cp --acl public-read /var/log/dmesg "$aws_url/logs/dmesg"
        aws s3 cp --acl public-read /tmp/plackup-access.log "$aws_url/logs/plackup-access.log"
        aws s3 cp --acl public-read /tmp/plackup-error.log "$aws_url/logs/plackup-error.log" )
    fi
after_success:
  - |
    if [ "$COVERAGE" == "1" ] ; then
       curl http://localhost:5001/stop.pl ;
       while [ -n "$(jobs -r | grep ledgersmb-server.psgi)" ] ; do sleep 1; echo -n "." ; done ;
       echo "" ;
    fi
  - coverage-report
  # display the available resources
  - utils/diagnostics/t/01-system-resources.t
  # try and force the github camo.githubusercontent.com cache to refresh our badges
  # with no arguments, this only refreshes the badge assests linked to by the default page shown when visiting
  # https://github.com/ledgersmb/LedgerSMB
  # if we want to refresh assets other than those (ie: not master branch) then we will need to add explicit arguments to do so
  # the script is sourced from https://github.com/sbts/github-badge-cache-buster but isn't expected to change so there is no point making it a submodule
  - utils/test/github-badge-cache-buster.sh

after_failure:
  # display the available resources
  - utils/diagnostics/t/01-system-resources.t
  - echo ===============================
  - echo === dmesg                   ===
  - echo ===============================
  - cat /var/log/dmesg
  # display the dmesg log. may give some hints about system related failures. eg: has the OOM killer triggered
  - echo ===============================
  - echo === /tmp/plackup-access.log ===
  - echo ===============================
  - cat /tmp/plackup-access.log
  - echo
  - echo ===============================
  - echo === /tmp/plackup-error.log ===
  - echo ===============================
  - cat /tmp/plackup-error.log
  - echo
  - echo ===============================
  - echo === /tmp/${BROWSER}.log ===
  - echo ===============================
  - egrep -v "DevTools request|dbus-daemon|D-BUS daemon" /tmp/${BROWSER}.log

