/** @format */

define([
   "dojo/ready",
   "dojo/parser",
   "dojo/has",
   "lsmb/html/credentials_html",
   "lsmb/html/login_html",
   "lsmb/html/payments2_html",
   /* dojo-data-type references in elements.html */
   /* "dijit/form/Button",
   "dijit/form/CheckBox",
   "dijit/form/CurrencyTextBox",
   "dijit/form/MultiSelect",
   "dijit/form/NumberTextBox",
   "dijit/form/RadioButton",
   "dijit/form/Select",
   "dijit/form/ToggleButton",
   "dijit/form/ValidationTextBox",
   "lsmb/DateTextBox",
   "lsmb/ResizingTextarea", */
   /* Every reference */
   "dijit/Dialog",
   "dijit/form/Button",
   "dijit/form/CheckBox",
   "dijit/form/ComboBox",
   "dijit/form/CurrencyTextBox",
   "dijit/form/MultiSelect",
   "dijit/form/NumberSpinner",
   "dijit/form/NumberTextBox",
   "dijit/form/RadioButton",
   "dijit/form/Select",
   "dijit/form/Textarea",
   "dijit/form/TextBox",
   "dijit/form/ToggleButton",
   "dijit/form/ValidationTextBox",
   "dijit/layout/BorderContainer",
   "dijit/layout/ContentPane",
   "dijit/layout/TabContainer",
   "dijit/Tooltip",
   "lsmb/accounts/AccountSelector",
   "lsmb/DateTextBox",
   "lsmb/Form",
   "lsmb/Invoice",
   "lsmb/InvoiceLine",
   "lsmb/InvoiceLines",
   "lsmb/journal/fx_checkbox",
   "lsmb/layout/TableContainer",
   "lsmb/MainContentPane",
   "lsmb/menus/Tree",
   "lsmb/parts/PartDescription",
   "lsmb/parts/PartSelector",
   "lsmb/PrintButton",
   "lsmb/PublishCheckBox",
   "lsmb/PublishRadioButton",
   "lsmb/PublishSelect",
   "lsmb/PublishToggleButton",
   "lsmb/Reconciliation",
   "lsmb/ReconciliationLine",
   "lsmb/reports/ComparisonSelector",
   "lsmb/reports/PeriodSelector",
   "lsmb/ResizingTextarea",
   "lsmb/SetupLoginButton",
   "lsmb/SimpleForm",
   "lsmb/SubscribeCheckBox",
   "lsmb/SubscribeSelect",
   "lsmb/SubscribeShowHide",
   "lsmb/TemplateManager",
   "lsmb/users/ChangePassword"
], function (ready, parser) {
   ready(1, function () {
      parser.parse();
   });
   return {};
});
